### PR TITLE
Integrate MotherTongues index building, scoring, and serialization into FV backend

### PR DESCRIPTION
**Pull request by roedoejet**
## High-Level Description of Problem & Changes

The new, in-development PWA front ends will consume data in the MTD data format. The `mothertongues` library uses Pydantic to specify this format and to parse, validate, and serialize dictionary configurations and entries. In order for language-specific, approximate, multi-field search to function offline on the PWA, the front end will need:

- An inverted index containing all L1 and L2 terms and postings.
- A list of the raw dictionary data, formatted according to `mothertongues`'s `DictionaryEntry` spec.
- A configuration (dict) containing information about the dictionary and other settings such as how to normalize search queries to match the normalized terms in the indices.

The implementation in this PR defines [a task](https://github.com/First-Peoples-Cultural-Council/fv-be/blob/846a17e9ecf0c02fb16422fcedb6403c723e5d9b/firstvoices/backend/tasks/build_mtd_export_format.py) for querying data from the database, building the required inverted index, and serializing everything into JSON which is then saved to the database. This PR also exposes an endpoint for retrieving the data for a specific site (`/api/1.0/sites/<site_slug>/mtd-data`).

This is a draft PR because there are a number of possible directions and I want to make sure you all agree on the direction before I commit too much time on it! I realize there is a lot here, and so please don't hesitate to comment or we can also schedule a call to discuss. I've itemized the main outstanding issues below.

### Outstanding Issues
- [ ] Is the site data api used for anything else? Or is the only purpose to provide data to the PWA's? If its only purpose is to provide data to the PWA's, I can just replace the existing `/api/1.0/sites/<site_slug>/data` functionality with the one at `/api/1.0/sites/<site_slug>/mtd-data`. 

There is no other use for this endpoint. We should replace the old endpoint with this one.

- [x] Where and when should the task be triggered? Chron job? Through another API call? 
        The task can be run manually right now with:
        
         ❯ python manage.py shell
         >>> from backend.tasks.build_mtd_export_format import build_index_and_calculate_scores
         >>> build_index_and_calculate_scores(<site_slug>)
        
Do it on save. Only when a public `DictionaryEntry` gets saved/edited/deleted. This task will be done by FV dev team: FW-5349.

Consider caching options for endpoint. This task will be done by FV dev team: FW-5350

- [x] Should we be storing multiple MTD export builds? Or just overwrite the last build every time the task is run?

Just save the latest.

- [ ] How and where do you want to store site-specific configuration information? I imagine most of this will either stay the same between sites, or is easily queried from the database (like the language name). However, there are also some language-specific configurations such as [the normalization transducer](https://github.com/First-Peoples-Cultural-Council/fv-be/blob/846a17e9ecf0c02fb16422fcedb6403c723e5d9b/firstvoices/backend/tasks/build_mtd_export_format.py#L76) which normalizes search terms in the front end and the inverted index, and the configuration for weighting different types of substitutions when calculating the edit distance in the approximate search algorithm. How will you be creating and updating this information and what is the preferred way and location to store it? 

We need to decide where to store RestrictedTransducer (i.e. normalization transducer) configurations for each site: FW-5351

We also need to decide where to store weighted transducer configurations: FW-5172

- [x] `mothertongues` currently only accepts a single image, whereas the initial API allowed a list. Is this a problem? See [here](https://github.com/First-Peoples-Cultural-Council/fv-be/blob/846a17e9ecf0c02fb16422fcedb6403c723e5d9b/firstvoices/backend/serializers/site_data_serializers.py#L117) for details on my interim implementation.

For now, keep as just picking the first image.

- [ ] `mothertongues` currently only accepts a single associated theme and a single associated 'secondary theme' for each entry. Is this a problem? See [here](https://github.com/First-Peoples-Cultural-Council/fv-be/blob/846a17e9ecf0c02fb16422fcedb6403c723e5d9b/firstvoices/backend/serializers/site_data_serializers.py#L124C25-L124C25) and [here](https://github.com/First-Peoples-Cultural-Council/fv-be/blob/846a17e9ecf0c02fb16422fcedb6403c723e5d9b/firstvoices/backend/serializers/site_data_serializers.py#L150) for details on my interim implementation

I think we should change this in MTD actually. Maybe a list of tuples, or a list of dictionaries.

- [ ] We do want video.

Maybe FV dev team will do a PR.

- [ ] Maybe adding read-along stuff.

- [ ] I am assuming that we want to continue sorting the entries separately, but if we want `mothertongues` to sort the entries instead, we need to change [this line](https://github.com/First-Peoples-Cultural-Council/fv-be/blob/846a17e9ecf0c02fb16422fcedb6403c723e5d9b/firstvoices/backend/tasks/build_mtd_export_format.py#L112).

Continue sorting in FV!

### Checklist
- [x] README / documentation has been updated if needed
- [ ] PR title / commit messages contain Jira ticket number if applicable (I don't have access to the FPCC Jira, feel free to edit the PR title as necessary, or let me know how I should amend the commit messages)
- [x] Tests have been updated / created if applicable 
- [N/A] Admin Panel has been updated if models have been added or modified (I haven't done this yet, pending answers to the questions above!)
- [x] Migrations have been updated and committed if applicable
- [ ] Team Postman workspace has been updated if applicable

### Reviewers Should Do The Following:
- [ ] Please comment on this possible direction for integration
- [ ] Please comment/reply to my specific questions below
- [ ] Review the code changes here
- [ ] Pull the branch and test locally

### Additional Notes
N/A

### CODE REVIEW

**Comment by roedoejet** [comment]
> 2.7% Duplication

The 'code smells' seem to be because I have `TODO:` in a few places - but these are legitimate (until fixed!).

**Comment by sarahfirstvoices** [comment]
Some jira numbers:
* FW-5349 - updating the index when a DictionaryEntry is saved
* FW-5350 - caching for the endpoint
* FW-5351 - normalization transducers

**Review by sarahfirstvoices — APPROVED** [review]

**Comment by roedoejet** [comment]
@sarahfirstvoices - I just rebased onto main and added the following changes:

- log warnings when entries don't pass validation (with test)
- filter entries to public only (with test)

As we discussed, I'll leave the following to other PRs:

- Removing the old `/api/1.0/sites/<site_slug>/data` endpoint 
- Triggering the MTD indexing and scoring task when a public DictionaryEntry gets saved/edited/deleted: FW-5349
- Developing a caching mechanism for the endpoint: FW-5350
- Deciding where to store RestrictedTransducer (i.e. normalization transducer) configurations for each site: FW-5351
- Deciding where to store weighted transducer configurations: FW-5172
- Supporting `video` as part of a DictionaryEntry
- Supporting readalongs for example sentences
- Supporting more than one category
- Guru dev team will be directed to use separate `categories` endpoint.

**Comment by roedoejet** [comment]
Great to chat yesterday @sarahfirstvoices ! Once this is merged in, is there any extra steps needed to make sure the new endpoint is available so I can make the related PR on the front-end repo?

**Comment by roedoejet** [comment]
> Great to chat yesterday @sarahfirstvoices ! Once this is merged in, is there any extra steps needed to make sure the new endpoint is available so I can make the related PR on the front-end repo?

Or actually, are they just running the backend locally anyways? I'm taking today off (food poisoning booooo!) but I'm hoping to make a PR to them soon.

**Comment by bronson-c** [comment]
Just a heads-up, I have just merged another PR including a migration so the migration in this PR will need to be updated before merging. Thank you!

**Comment by sarahfirstvoices** [comment]
@roedoejet Hope you are feeling better! This is merged and I'll get it promoted to the preprod environment that the Guru devs are using. You should be all set for that frontend PR. Thanks so much!

**Comment by roedoejet** [comment]
> Just a heads-up, I have just merged another PR including a migration so the migration in this PR will need to be updated before merging. Thank you!

Thanks @sarahfirstvoices - I think maybe the migration didn't get fixed before merging? sorry, I should have clarified and asked whether I should have done that or if someone else would do it before merging!

**Comment by roedoejet** [comment]
@sarahfirstvoices , I added a PR here: https://github.com/First-Peoples-Cultural-Council/fv-be/pull/729 which I think fixes the issue @bronson-c described.

**Pull request merged**
